apiVersion: v1
kind: Service
metadata:
  name: servicea-service
  labels:
    app: servicea
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: servicea
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: servicea-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
      - name: servicea
        image: SERVICE_TAG_A:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        envFrom:
        - configMapRef:
            name: mp-istio-sample-config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /serviceA
        backend:
          serviceName: servicea-service
          servicePort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: serviceb-service
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: serviceb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: serviceb-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceb
    spec:
      containers:
      - name: serviceb
        image: SERVICE_TAG_B:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mp-istio-sample-config
  namespace: default
data:
  prop1: val1
  prop2: val2
